[package]
name = "asmdoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
argh = "0.1.12"
logos = "0.14.1"
paste = "1.0.15"
serde = "1.0.208"
serde_toml = "0.0.1"
toml = "0.8.19"
walkdir = "2.5.0"
